# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - cicd-ang-test

on:
  push:
    branches:
      - wb-app-srvc
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
      with:
        ref: wb-app-srvc

    - name: Setup Node 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cicd-ang-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_086e7ecf5962487e9104ce34c5043f21 }}
        package: .